apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: project
  name: project-leader-election-rolebinding
  namespace: project-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: project-leader-election-role
subjects:
- kind: ServiceAccount
  name: project-controller-manager
  namespace: project-system
